### ISSUE TITLE
alive_bar in Python 3.9 has no "hollow" style so build fails

### ISSUE THREAD

**Issue by ajkessel** [sapianco/slack-matrix-migration#1]
migrate.py fails due to lack of "hollow" as an alive_bar style in Python 3.9 library:
```
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/sapianco-QcjPQkuU/lib/python3.9/site-packages/alive_progress/core/configuration.py", line 135, in validator
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/src/matrix/sapianco/slack-matrix-migration/slack-matrix-migration/migrate.py", line 951, in <module>
    main()
  File "/home/user/src/matrix/sapianco/slack-matrix-migration/slack-matrix-migration/migrate.py", line 894, in main
    roomlist_channels = migrate_rooms(jsonFiles["channels.json"], config, admin_user)
  File "/home/user/src/matrix/sapianco/slack-matrix-migration/slack-matrix-migration/migrate.py", line 440, in migrate_rooms
    with alive_bar(len(channelData), bar = 'hollow', spinner = 'waves2') as bar:
  File "/home/user/.local/share/virtualenvs/sapianco-QcjPQkuU/lib/python3.9/site-packages/alive_progress/core/progress.py", line 93, in alive_bar
    config = config_handler(**options)
  File "/home/user/.local/share/virtualenvs/sapianco-QcjPQkuU/lib/python3.9/site-packages/alive_progress/core/configuration.py", line 125, in create_context
    local_config = {**global_config, **_parse(theme, options)}
  File "/home/user/.local/share/virtualenvs/sapianco-QcjPQkuU/lib/python3.9/site-packages/alive_progress/core/configuration.py", line 149, in _parse
    return {k: validator(k, v) for k, v in options.items()}
  File "/home/user/.local/share/virtualenvs/sapianco-QcjPQkuU/lib/python3.9/site-packages/alive_progress/core/configuration.py", line 149, in <dictcomp>
    return {k: validator(k, v) for k, v in options.items()}
  File "/home/user/.local/share/virtualenvs/sapianco-QcjPQkuU/lib/python3.9/site-packages/alive_progress/core/configuration.py", line 140, in validator
    raise ValueError(f'invalid config value: {key}={value!r}')
ValueError: invalid config value: bar='hollow'
```

Changing "hollow" to some other style fixes the problem, e.g.

```
index c1ac17a..5c9c80f 100644
--- a/slack-matrix-migration/slack-matrix-migration/migrate.py
+++ b/slack-matrix-migration/slack-matrix-migration/migrate.py
@@ -437,7 +437,7 @@ def migrate_rooms(roomFile, config, admin_user):

     # channels
     channelData = json.load(roomFile)
-    with alive_bar(len(channelData), bar = 'hollow', spinner = 'waves2') as bar:
+    with alive_bar(len(channelData), bar = 'bubbles', spinner = 'waves2') as bar:
         for channel in channelData:
             if config["skip-archived"]:
                 if channel["is_archived"] == True:
```
alive_progress from github reports only these styles (no "hollow"): classic stars twirl twirls horizontal vertical waves waves2 waves3 dots dots_waves dots_waves2 it ball_belt balls_belt triangles brackets bubbles flowers elements loving notes notes2 arrow arrows arrows2 arrows_in arrows_out radioactive boat fish fish2 fishes crab frank wait wait2 wait3 pulse

**Comment by arpagon** [comment]
Fixed in #2
